### ISSUE TITLE
plans for 1.14?

### ISSUE THREAD

**Issue by WarriorGamingserv** [ProjectKorra/ProjectKorra#1001]
Hey, so i run an RPG server where i use project korra for the 'magic' it is still called bending but, i want to upgrade to 1.14 and was wondering if there are any plans for it?

**Comment by Simplicitee** [comment]
Yes there are plans to update to 1.14.

**Comment by WarriorGamingserv** [comment]
exactly how long do you think it would be? cause i want to upgrade my server to 1.14

**Comment by ChristopherWMM** [comment]
> exactly how long do you think it would be? cause i want to upgrade my server to 1.14

We do not have an estimated timeline yet, expect one when we begin the final testing phase of the current release cycle. If you want to compile the bleeding version yourself, do so from the `1.13` branch. (Dumb name, I know)
