### ISSUE TITLE
AirBlast's EntityPush doing nothing

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1006]
_As title suggests,_ **AirBlast's EntityPush is doing nothing.**
I have set EntityPush to 0 and SelfPush to 2.65 and I can still push other mobs/entities
Doing the reverse and setting EntityPush to 2.65 and SelfPush to 0 makes it so that airblast pushes nothing at all, further proving EntityPush doing nothing.

**Comment by ChristopherWMM** [comment]
Thanks for the report, the issue has been found.

For future reference: https://github.com/ProjectKorra/ProjectKorra/blob/1.13/src/com/projectkorra/projectkorra/airbending/AirBlast.java#L144-L145

**Comment by ChristopherWMM** [comment]
Fixed as of #1008
