### ISSUE TITLE
AirAgility remaining Active during Sneak [PK 1.8.9 Beta]

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1011]
As title suggests, AirAgility Speed & Jump boost passives are staying active even while the player is crouching.

**How to recreate:**
Simply sprint in order to activate the AirAgility passive, and then hold sneak and you will maintain the passive unless something slows you down (such as walking into a wall)

**Comment by Simplicitee** [comment]
You can sneak and sprint at the same time so this is normal behavior (sounds weird but is true)

**Comment by xNuminousx** [comment]
Should this be closed then?
