### ISSUE TITLE
Suffocate usable under water and behind walls

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1012]
Using Suffocate on a target and then hiding behind a wall makes player able to suffocate target with the suffocate ability still active.
Also, Suffocate is usable underwater.

**Comment by xNuminousx** [comment]
lol, suffocate underwater

**Comment by ChristopherWMM** [comment]
I am going to, for now, say that underwater suffocate is okay. Suffocating from behind walls has been fixed as of #1009
