### ISSUE TITLE
Water block removes after it was affected with raise earth

### ISSUE THREAD

**Issue by AIRBEST** [ProjectKorra/ProjectKorra#1015]
Water block removes after it was affected with raise earth. 
How to recreate: use RaiseEarth below any water block and collapse it. 
It will stay forever and will not be regenerated.

<p><a href="https://user-images.githubusercontent.com/54533835/63684633-6ddfed80-c80e-11e9-9a7b-83870b7ed3ea.gif">gif file</a></p>

**Comment by Varhagna** [comment]
This was resolved.
