### ISSUE TITLE
Water source remains after breaking source

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1018]
Sourcing for a water ability so that the particles appear and then removing the original source will make particles still present, which can make the ability used as usual.
[Press here for gif.](https://media.giphy.com/media/iEq9IlALfkKj4TD4tP/giphy.gif)

**Comment by xNuminousx** [comment]
I've fixed this for the Surge gif you showed on my local repo. Will have to go through the other water abilities and see where it needs to be applied.

**Comment by Varhagna** [comment]
Fixed by #1069
