### ISSUE TITLE
Duping items with PhaseChange

### ISSUE THREAD

**Issue by Thijmen3** [ProjectKorra/ProjectKorra#1045]
You can dupe items with phase change, when a player places a chest in the water and freezes the water the chest gets destroyed and drops the items but when you change the ice back to water the chest is back with the same items in it.

**Comment by ChristopherWMM** [comment]
Thanks for the report, we will confirm this and try to have a hot fix for this in the latest version ASAP

**Comment by ChaoZed** [comment]
Hey, I'm trying to recreate and record this bug on the latest PK version but don't seem to be able to recreate the bug. Could you provide steps on how to recreate this? Also, what version PK did you do it on?

I'm trying to PhaseChange and then melt a chest in the water but it doesn't do anything of the sort that you mentioned

**Comment by ChaoZed** [comment]
Hey nevermind, I was able to recreate this.
Video:
https://streamable.com/5e33d

**Comment by Varhagna** [comment]
Closed by #1064
