### ISSUE TITLE
Outdated ProjectKorra still shows as green in /pl

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1046]
As title suggests, an outdated version of ProjectKorra still shows up as functioning when checking the plugins list.

PK Version: 1.8.7
MC Version: 1.14.4

Old issue that works on every version, but has never been fixed ¯\_(ツ)_/¯

**Comment by ChristopherWMM** [comment]
Thanks for the report, after a quick reading I think this would entail that we make each version keep track of what versions it can/cannot work with? We will look into this further.
