### ISSUE TITLE
[PK 1.8.9] Source AirSuction stays when toggling bending off

### ISSUE THREAD

**Issue by ChaoZed** [ProjectKorra/ProjectKorra#1049]
As title says.
Video evidence:
https://streamable.com/7yef3

Note: My AirSuction radius in the config is set to 15 blocks. I went way over 30 blocks but it still remained. The AirSuction should just disperse as soon as my bending is toggled off. I would be able to bend and whatnot and those particles would be there for as long as I didn't refresh airsuction by using it.

**Comment by xNuminousx** [comment]
You're also staying in AirSpout after toggling bending?

**Comment by Varhagna** [comment]
Fixed by #1050
