### ISSUE TITLE
Update KingdomsX dependency

### ISSUE THREAD

**Issue by AaronStrange3** [ProjectKorra/ProjectKorra#1088]
https://pastebin.com/uR4yPZuC

Pretty sure all that needs to happen is PK updates from kingdoms to KingdomsX.  Songoda has stopped development on kingdoms, and KingdomsX is the only kingdoms version that works for 1.16

Sorry if you already know this or anything. I just didn't see anything here for it and thought I might as well add it, since it is an issue.

**Comment by Varhagna** [comment]
Thank you for bringing this to our attention.

**Comment by BumperPlaysGames** [comment]
Yall really need to fix this, bending doesn't work with kingdomsx.
