### ISSUE TITLE
KingdomsX/ProjectKOrra

### ISSUE THREAD

**Issue by BumperPlaysGames** [ProjectKorra/ProjectKorra#1097]
https://pastebin.com/j8xsen3U

Instead of fable kingdoms, use KingdomsX, its better.

**Comment by Aztlon** [comment]
If you hadn't noticed, this is already an issue (even before the other issue you just created). It's being taken care of already.

**Comment by BumperPlaysGames** [comment]
thank you, when do you think it will be fixed?

**Comment by Aztlon** [comment]
I'm not sure. It's not up to me at this point.
