### ISSUE TITLE
Fix FireBlast going through liquids

### ISSUE THREAD

**Issue by Aztlon** [ProjectKorra/ProjectKorra#1098]
The recent firebending refactor accidentally removed the FireBlast removal upon contact with liquids. Now FireBlast can travel through water and possibly lava, though I haven't tested the latter.
I've fixed this on my servers already, and I can make a PR that fixes this, but I think I need to rebase my fork before I do that, which is waiting on my current PR. There's no rush, though; I just wanted to make sure you were aware of the bug. I'll try making different branches in the future if that helps; sorry, I'm still pretty new to contributing on GitHub.

**Comment by StrangeOne101** [comment]
May as well get an extra PR in ;)
