### ISSUE TITLE
Catapult Duplication Glitch

### ISSUE THREAD

**Issue by Varhagna** [ProjectKorra/ProjectKorra#1103]
At the moment Catapult places a duplicate block on top of the original rather than moving it.

**Comment by Aztlon** [comment]
Are you sure? Looks like it pulls up the top 3 blocks.
![catapult](https://user-images.githubusercontent.com/59033980/95628426-073a8500-0a4c-11eb-9b32-deac9b83048d.png)

**Comment by Varhagna** [comment]
I didn't set it as confirmed because I wasn't sure, someone posted about it in bug reports and I made it into an issue

**Comment by Aztlon** [comment]
> I didn't set it as confirmed because I wasn't sure, someone posted about it in bug reports and I made it into an issue

Oh ok, sorry! I didn't realize that.

**Comment by ChristopherWMM** [comment]
It appears as though @Aztlon is correct. In the event the moved blocks are broken they do not revert. No duplication appears to happen.
