### ISSUE TITLE
BlockFromToEvent & BlockFadeEvent huge lag

### ISSUE THREAD

**Issue by ludgart** [ProjectKorra/ProjectKorra#1113]
Hello,

I have some lag issues with ProjektKorra. I'm using ProjektKorra version 1.9.0 on a 1.16.3 paperspigot server.

Timings report: https://timings.aikar.co/?id=2e4866ed61cd491b807c6639af2b2221
Spark profiler report: https://spark.lucko.me/#3eoll8kXxL
I already disabled the WaterManipulation and PhaseChange abilities without success.

It look like the issue come from here: https://github.com/ProjectKorra/ProjectKorra/blob/f39c7f7186ff0e31c1190497d770a3abcc493012/src/com/projectkorra/projectkorra/ability/WaterAbility.java#L240

What can I do?

Regards
ludgart

**Comment by ChristopherWMM** [comment]
Thanks for bringing this to our attention, we will investigate the performance issue.
