### ISSUE TITLE
BendingBoard not enabling when you login

### ISSUE THREAD

**Issue by Loonyy** [ProjectKorra/ProjectKorra#1121]
When you relog your board gets hidden and you have to use /b board **twice** to enable it again.

https://gyazo.com/a7df4e3e10706b77ec7cef2ef40059ad

**Comment by ChristopherWMM** [comment]
Is this on every relog or only in special cases? We do not have this issue pinpointed so any clarification would be greatly appreciated!

**Comment by Loonyy** [comment]
-- Update --
There may be other causes, but this is the one I found:
When you leave the server with an ability on cooldown, and then log back in **after** that ability is off cooldown, your board will be broken.
