### ISSUE TITLE
WallOfFire & AirScooter

### ISSUE THREAD

**Issue by Loonyy** [ProjectKorra/ProjectKorra#1122]
You can passthrough WOF on AirScooter and not take damage (sometimes you do take damage but most times you don't)
Same is true for other air moves such as AirBlast, I imagine it's a speed issue

https://gyazo.com/fada7d244bc839f80140cb5511e97f59

**Comment by ChristopherWMM** [comment]
@Loonyy I believe this can be accomplished by decreasing the damage interval config option for WallOfFire (`"Abilities.Fire.WallOfFire.DamageInterval"`) so it happens more often. By default, it runs every 500ms but this may be too infrequent. Let us know if you find a better value.
