### ISSUE TITLE
PhaseChange Lets Waterbenders Irrigate the Nether

### ISSUE THREAD

**Issue by Shadow8472** [ProjectKorra/ProjectKorra#1173]
Waterbenders can place down ice and PhaseChange it to a normal water source block in the nether. Water will flow and even create additional source blocks.

**Comment by MKieburtz** [comment]
I'm interested in what the devs think should happen when using phase change in the nether.

**Comment by Shadow8472** [comment]
From the support channel on the plugin Discord:

> OmniCypher — 09/30/2021
> I think we sorta need to identify what the proper behavior should be for phase change
> [4:20 AM]
> Waterbenders have, for as long as I remember, been able to freeze water / melt ice permanently with phase change
> [4:20 AM]
> So I think it is more of a “in the nether the ice should go away but no water should be placed”
https://discord.com/channels/292809844803502080/300990411353358336/893094603627057213

**Comment by ChristopherWMM** [comment]
Fix merged into `wip`.
