### ISSUE TITLE
Fire Blocks from Firebending Don't Spread With FireGriefing True

### ISSUE THREAD

**Issue by Shadow8472** [ProjectKorra/ProjectKorra#1174]
Lingering fire from FireBlast, FireJet, and FireBurst doesn't spread. 
FireJet even calls identical code after passing/failing its FireGriefing check.

It would be nice if TempFire could make a FireGriefing check (regardless of material [normal/soul fire]) to spread normal fire per vanilla mechanics, though something might need to be done so Blaze continues to work as expected.

Secondary fire from Combustion works as expected.

**Comment by ChristopherWMM** [comment]
Hello, thanks for bringing this issue to our attention. I need to look into it a little further but I am almost wondering that if fire griefing is on, should we just place normal fire as opposed to temp fire?

**Comment by Shadow8472** [comment]
I'm assuming normal fire is what was used back when I was playing bending on Minecraft 1.6.

The biggest issue is BlueFire. It doesn't spread on its own. If it's supposed to have that slight edge, it really should spread as readily as normal firebending.

The best quick, but partial fix I can think of would be for lingering fire to add a flint+steel action upon going out. Firebenders could again light caves with permaburn blocks + bending. It would be neat to see blue fire go normal or vice versa to match its netherrack/soulsand/soil base block.
