### ISSUE TITLE
WaterArms Activation delay

### ISSUE THREAD

**Issue by KWilson272** [ProjectKorra/ProjectKorra#1191]
Occasionally when trying to activate one of WaterArms' abilities it won't respond. This is most noticeable when using spear and grapple, and especially noticeable when the player attempts to fire an ability off while moving at the same time.

I've tracked the issue to the canPlaceBlock() method in the WaterArms class, and more specifically the 'external.contains()' check within that method. It appears that the 'external' set is what's being used to store the TempBlocks that make up the arms; and the canPlace method is returning false if the block it's checking is in that 'external' set.

The value returned in the canPlaceBlock() method is being used in displayRightArm(), displayLeftArm(), and canDisplayActiveArm(). These methods are then used in the WaterArms Spear and Whip classes when activating or progressing the ability. The canPlaceBlock() method returning false when the checked block is part of the 'external' set then prevents the ability from properly activating. 

Removing lines 208-213 from the canPlaceBlock() method in the WaterArms class fixed the issue. We had testers play around with the fix over the course of a month and no issues were encountered.

**Comment by ChristopherWMM** [comment]
Thanks for the insight @KWilson272, how about you make a PR of your changes to the `wip` branch so we can properly review them?
