### ISSUE TITLE
Global Presets

### ISSUE THREAD

**Issue by olepoeschl** [ProjectKorra/ProjectKorra#1200]
Hi, I want the system to have global presets, so I edited presets.yml using the example as layout preset and started the server, but unfortunately the presets are not visible to anybody. Maybe it's a bug or maybe I just unterstood it wrong, sorry if that is the case.

Please have a look at my presets.yml. I renamed it for easier uploading here
(After starting the server, its formatting changed a bit)
[presets.txt](https://github.com/ProjectKorra/ProjectKorra/files/7836104/presets.txt)

PS: Love the plugin

**Comment by ChristopherWMM** [comment]
Hello @olepoeschl, thanks for making the issue. Do your players have the `bending.command.preset.bind.external` permission node? This is required to bind presets from the global preset file and is not given by default.

**Comment by olepoeschl** [comment]
That was the problem. Thank you so much and sorry for the circumstances.
