### ISSUE TITLE
Security issue : SQL Injection

### ISSUE THREAD

**Issue by fengonne** [ProjectKorra/ProjectKorra#1211]
By reading how you insert data inside your database, I'have seen that your are not using prepare statement. Which is the only way to avoid SQL injection.

I think it's can be a nice feature to improve DB access security.

**Comment by StrangeOne101** [comment]
Can you give an example on where this would cause a vulnerability? As far as I can see, creating a preset would be one of the only ways to do it, but that does use prepared statements

**Comment by DomiRusz24** [comment]
May not be specialized in this, but I do recall checking on the SQL code here (always fun to spot this rookie mistake). And found nothing, so as a complete rando, I think it's fine, just as StrangeOneOneZeroOne said.

**Comment by StrangeOne101** [comment]
Closing for now, since we haven't found anything that can be executed from a client to cause SQL Injection and the author of the issue has not commented further. 

Please reopen the issue if you feel this is incorrect.
