### ISSUE TITLE
Source block selection range of 0 can result in a crash

### ISSUE THREAD

**Issue by ChristopherWMM** [ProjectKorra/ProjectKorra#1212]
We use [LivingEntity::getTargetBlock(Set,int)](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/LivingEntity.html#getTargetBlock(java.util.Set,int)) to look for source blocks a lot. This wraps the usage of a [BlockIterator](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/util/BlockIterator.java#52) in Spigot which has the precondition that a maxDistance of 0 yields an unlimited search range. Currently, if a server owner sets the select range of an ability to 0 (or some value between 0 and 1 due to integer truncation) it will continuously look for a source block and can result in a complete server crash.

We will want to likely prevent this by stopping unlimited searches by not allowing 0 as a select range and likely sending a warning to server owners.

**Comment by StrangeOne101** [comment]
Fixed in #1214
