### ISSUE TITLE
Blocks can be placed inside of Temp water blocks

### ISSUE THREAD

**Issue by StrangeOne101** [ProjectKorra/ProjectKorra#1216]
# Issue
Blocks can be placed inside water temp blocks, such as surge shield. This causes the blocks to be lost forever and not even refunded into the inventory.

However, we cannot completely deny this action, either. As phase change melts ice into water, and players should still be able to place blocks in the water

**Comment by Simplicitee** [comment]
This is simply the tempblock needing to be destroyed when a player overrides it by placing something there.

**Comment by StrangeOne101** [comment]
I thought so too. But it isn't enough. TempBlocks are already removed when a player places a block there, but this still happens.

**Comment by Simplicitee** [comment]
Probably something to do with the badness that is TempBlock constructor then

**Comment by StrangeOne101** [comment]
Re-opened because this isn't 100% solved. It was fixed for WaterSpout deleting blocks, but abilities like Surge shield still do it

**Comment by JustAHuman-xD** [comment]
With the more recent changes to temp blocks is this still a problem?

**Comment by StrangeOne101** [comment]
I believe it is still an issue for Surge shield since it doesn't always use Temp blocks...? Will need to be retested
