### ISSUE TITLE
The bending board still shows even without permission to use it

### ISSUE THREAD

**Issue by StrangeOne101** [ProjectKorra/ProjectKorra#1240]
# Description
The bending board is still visible even when a player doesn't have the `bending.command.board` permission

**Comment by Dreig-PSD** [comment]
isn't it permission for *command* /b board?
So, without permission, player can't toggle the board, but can see it, because it's default.

**Comment by StrangeOne101** [comment]
> isn't it permission for _command_ /b board?
> So, without permission, player can't toggle the board, but can see it, because it's default.

Yes, this is the permission for the bending board command. But if you take away all bending permissions so a player cannot bend, the bending board still shows. Therefore, the bending board should hide if the player doesn't have this permission node

**Comment by Dreig-PSD** [comment]
> > isn't it permission for _command_ /b board?
> > So, without permission, player can't toggle the board, but can see it, because it's default.
> 
> Yes, this is the permission for the bending board command. But if you take away all bending permissions so a player cannot bend, the bending board still shows. Therefore, the bending board should hide if the player doesn't have this permission node

May be will be better to add new permission bending.board?
And of course new config field -
.Board.Default: true

**Comment by StrangeOne101** [comment]
I think that if they can't use the board command, they shouldn't be able to see it. Since we always want the board to be optional.

We could add a default config option for it though. If it starts hidden or not

**Comment by StrangeOne101** [comment]
Fixed in 7a9cfbc5d9397b831b508f8eaba9a52b86a90985
