### ISSUE TITLE
Make config option for how much bending is affected by armor

### ISSUE THREAD

**Issue by StrangeOne101** [ProjectKorra/ProjectKorra#1243]
# Description
Make a config option called `Properties.IgnoreArmorPercentage: 50.0`. This will allow bending to ignore that percentage of armor. At 100%, it will ignore armor completely. 

Currently, bending is affected by armor and makes bending pointless in a survival world where you can get armor. This config option will change that.

# Implementation
Already, DamageHandler has the option to ignore armor completely when dealing damage. This should give a good place to start.

**Comment by JustAHuman-xD** [comment]
Do you think this should be a per element percentage, or a global percentage?

**Comment by StrangeOne101** [comment]
I did wonder about doing it per element. But I also couldn't see a use case for where they would be different
