### ISSUE TITLE
Firebending causes duplication of items

### ISSUE THREAD

**Issue by MaikeruP** [ProjectKorra/ProjectKorra#1257]
**ProjectKorra version:** 1.10.2
**Paper version:** 1.19.2 (build 210)

Using firebending moves on various items, especially custom player heads, carpets, flowers, and other placed items will cause the item to break as an item but the item remains placed - essentially duping the item.

One of my players submitted this video footage of firebending duping a placed player head:
https://youtu.be/2TX0HmTiveY

This bug has the potential to dupe Slimefun items, which is extremely harmful.

**Reproduction steps:**
1. Choose fire as your element
2. Bind "blaze" (or another firebending move)
3. Use the move on a placed item
4. The item drops an item but remains placed

**Comment by MKieburtz** [comment]
Here's another example video from the pk discord showing the same behavior with the wheat  https://discord.com/channels/292809844803502080/752662470941999135/1027829058345635920

**Comment by DontMessWithDis** [comment]
Yup! players showed me this today. it definitely happens on my server too.

**Comment by StrangeOne101** [comment]
Should be fixed in the next update. Thanks for the report :+1:

**Comment by StrangeOne101** [comment]
Fixed in 1.11.0
