### ISSUE TITLE
NPE on slot change when Illumination is disabled

### ISSUE THREAD

**Issue by Leomelonseeds** [ProjectKorra/ProjectKorra#1267]
When Illumination is disabled in the config, an NPE shows up every time players change slots. This is because on `PlayerItemHeldEvent`, `Illumination#slotChange` calls `CoreAbility.getAbility(Illumination.class)` which returns `null` since Illumination is disabled. Then, since `BendingPlayer#canUsePassive` does not have a null check, NPE is thrown for `getElement()`. If this could be fixed soon, it would be much appreciated.

Stack trace: https://pastebin.com/Ay49V5GU

**Comment by StrangeOne101** [comment]
Fixed in 1.11.0
