### ISSUE TITLE
Dup Glitch With Blaze Ability

### ISSUE THREAD

**Issue by DontMessWithDis** [ProjectKorra/ProjectKorra#1269]
Not sure if this is meant to happen, but a player showed me today that if he uses a blaze ability on flowers and/or crops it duplicates the flower 10 fold. I think for every blaze its 10. So in seconds a player can get stacks of crops.

**Comment by MKieburtz** [comment]
Yep, this is a known issue but I don't think we have a github issue for it so thanks.

**Comment by MKieburtz** [comment]
This is actually a duplicate of #1257, so should probably be closed

**Comment by StrangeOne101** [comment]
As [MKieburtz](https://github.com/MKieburtz) said, this is a duplicate, so closing because of that.

But fret not! I believe the bug has been fixed, and should be in the next PK update! Thanks for the report! :)
