### ISSUE TITLE
Left click sourcing abilities require double clicking to source

### ISSUE THREAD

**Issue by Legendary-Ocean** [ProjectKorra/ProjectKorra#1277]
If DynamicSourcing is true in the config, the resource selection is broken in the abilities that select resources with left click in some Water and Earth abilities. When you left click on a source, it will not be selected as a source, and when you left click second time, the first source you clicked will be selected.

[https://www.youtube.com/watch?v=d044rSq89MY](url)

Spigot: 1.19.3
Pk: 1.11.0

**Comment by StrangeOne101** [comment]
Can you confirm if this is fixed in 1.11.2 beta? I believe it should be

**Comment by Legendary-Ocean** [comment]
> Can you confirm if this is fixed in 1.11.2 beta? I believe it should be

Yes, totally fine.

**Comment by Legendary-Ocean** [comment]
Edit: only, when I turn off DynamicSourcing, still iceblast can be selected in water. Other than that, The left-click issue is completely resolved.

**Comment by StrangeOne101** [comment]
IceBlast is probably a separate issue. So maybe open a new big report for that

**Comment by Legendary-Ocean** [comment]
This problem has been fixed, I have never encountered with this in the last version. You can close this report.
