### ISSUE TITLE
Some passives are disabled in claims

### ISSUE THREAD

**Issue by StrangeOne101** [ProjectKorra/ProjectKorra#1278]
# Description
Some passives don't work in other people's claims, even if they are harmless to the environment

# Reports
- Illumination not working in Lands. Probably others too
- AirAgility, Tremorsense not working in Towny

**Comment by MKieburtz** [comment]
I can confirm this. Replicated on paper 1.19.3, towny 0.98.6.0, PK 1.11.0

**Comment by MKieburtz** [comment]
Got a report that flight also doesn't work in claims. Perhaps all harmless abilities are disabled in claims?

**Comment by StrangeOne101** [comment]
> Got a report that flight also doesn't work in claims. Perhaps all harmless abilities are disabled in claims?

Yep, exactly this. But this should be fixed now.
