### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by Nemesishh** [ProjectKorra/ProjectKorra#1302]
![image](https://github.com/ProjectKorra/ProjectKorra/assets/108588573/75836265-e256-4358-8208-fcf672fda1c5)

**Comment by JustAHuman-xD** [comment]
Can you provide more info? Full Logs, Minecraft version, ProjectKorra version etc. Without it we can't help you.

**Comment by Dreig-Michihi** [comment]
AvatachTweaks is the issue. Try to disable it's WaterSource effects in config.

**Comment by StrangeOne101** [comment]
Closed as it is related to AvatchTweaks
