### ISSUE TITLE
TempBlock Ice Suffocates players. Eg:Surge/Phasechange. PK 1.11.2 Spigot 1.20.1

### ISSUE THREAD

**Issue by SoraShiunin** [ProjectKorra/ProjectKorra#1309]
Title: Any type of generated ice will suffocate players.
Includes but probably not limited to:
- IceWave, Surge(Wave Freeze), Torrent(Freeze), WaterArms(Spear Freeze)
For some reason Jedcore Waterflow is not affected
(This is gamebreaking/gamechanging, in PvP/PvE freeze abilities are basically near-instant death prisons now)
Edit: Freezing water with octopusform...This ice will also suffocate.

**Comment by StrangeOne101** [comment]
I managed to fix this in the betas right

**Comment by StrangeOne101** [comment]
Fixed in 1.11.3
