### ISSUE TITLE
Using Lightning on a waterlogged copper slab will crash the server.

### ISSUE THREAD

**Issue by dniym** [ProjectKorra/ProjectKorra#1311]
When using lightning's ability with ArcOnCopper: true

if a player targets a copper slab that is waterlogged, the ability appears to go into an endless arc loop eventually crashing the server.

Steps for reproduction:
1) dig a hole
2) place copper slab
3) dump a bucket of water on it
4) target the block and use the lightning ability

Particles appear and just keep appearing, server eventually shuts down.

Note:  this does not happen with ArcOnIce: set to true, and water nearby

**Comment by PrideInt** [comment]
Fixed in: https://github.com/ProjectKorra/ProjectKorra/pull/1312
