### ISSUE TITLE
Feature request: keybinds

### ISSUE THREAD

**Issue by lylesnake** [ProjectKorra/ProjectKorra#1320]
This a super cool plugin, and this one feature tweak would make it perfect in my opinion. If we could bind it to any key, or at least the numpad 1-9, it would feel a lot more seamless and be way easier to use on the fly. The top row number keys correspond to your tools, making the default binding for this plugin really clunky. You have to make sure you have no tool in your inventory slot that is bound to the bending skill, so there are a lot of extra steps before you can activate a bending skill. I hope you can implement this change. Thank you

**Comment by MKieburtz** [comment]
We can only listen for keypresses that are bound to existing Minecraft actions. Like e for open inventory, or shift for crouch. If you haven't bound anything to the 'f' key, and press it, Minecraft doesn't send that to the server, and we can't listen to it.

**Comment by lylesnake** [comment]
Okay I understand. Thanks for the quick reply
