### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arkent112** [ProjectKorra/ProjectKorra#1353]
Hi, I am trying to use this plugin on my aternos server but it is not working' it is saying the plugin is working but when i try to do any skills it does nothing.

**Comment by LuxaelNivra** [comment]
You're probably playing on Minecraft 1.20.5 or above, you require Project Korra 1.11.3 where all of those problems are fixed, but Aternos does not have that version, you can either play on Minecraft 1.20.4 or use another hosting service (free or paid).

**Comment by arkent112** [comment]
aternos will have the new edition?

**Comment by LuxaelNivra** [comment]
Probably not, they take plugins from the Spigot page and they are currently unable to upload the new version there. Again, you can use other free hosting services which allow you to upload your own jars and even addon abilities.

**Comment by StrangeOne101** [comment]
As stated, Aternos only runs outdated versions of ProjectKorra. It's not something we can fix.
