### ISSUE TITLE
No permission node for bloodbending

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#233]
I pretty much had to guess to find this, but to enable bloodbending for players this is not listed anywhere or in the plugin.yml -> bending.water.bloodbending

**Comment by PhanaticD** [comment]
same with bending.air.flight

**Comment by OmniCypher-** [comment]
This issue is resolved in the latest build. There are two nodes for bloodbending
> bending.water.bloodbending.anytime: true

> bending.water.bloodbending: true
