### ISSUE TITLE
Exempt NCP noswing check when using suffocate

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#314]
Using suffocate triggers NCP's noswing check.

I would imagine any abilities that don't use a armswing (most that use shift) probably trigger this as well.

1.8.0 BETA 6

**Comment by OmniCypher-** [comment]
NCP as in NoCheatPlus? Is this still an issue in the latest builds?

**Comment by RoboMWM** [comment]
Yes, as in NoCheatPlus. I'll check if this is still an issue, for now I've worked around it with permission-based exemptions.

**Comment by curz46** [comment]
@RoboMWM status?

**Comment by RoboMWM** [comment]
Yup, still an issue.
