### ISSUE TITLE
Exempt NCP checks for shockwave/fireburst

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#320]
The following checks can be triggered when using shockwave, fireburst, or any AoE ability:
- entity out of line of sight (direction)
- attacking with too high a frequency (speed)
- improbable

1.8.0 BETA 6

**Comment by curz46** [comment]
@RoboMWM still an issue?

**Comment by RoboMWM** [comment]
Unsure, as I've currently exempted players from these checks. I'll see if I can reproduce later tonight or this weekend (to test, simply spawn a bunch of mobs around you, and use shockwave.)

**Comment by RoboMWM** [comment]
Yes, still an issue.
