### ISSUE TITLE
NullPointerException on isRegionProtectedFromBuildPostCache() in GeneralMethods.java due to GriefPrevention

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#328]
I was making some administrative claims via GriefPrevention, and it seems ProjectKorra is having issues checking for build protection? It's also likely that it could've been checking MobArena as well.

https://gist.github.com/RoboMWM/3e3e9d64dd7a81db197c

1.8.0 BETA 6

**Comment by OmniCypher-** [comment]
@RoboMWM, Can I get this re-confirmed with ProjectKorra 1.8.0?

**Comment by OmniCypher-** [comment]
This and issue #329 are most likely being caused by the same issue due to how similar the errors are and the nature of the plugins.
