### ISSUE TITLE
NullPointerException on isRegionProtectedFromBuildPostCache() in GeneralMethods.java due to PreciousStones

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#329]
Might be related to issue #328 - if PreciousStones is installed and integration is enabled in ProjectKorra, this gets spammed (as an earthbender at least):

https://gist.github.com/RoboMWM/da6a867b6fc011a504a4

Error disappears and abilities function as expected when integration is disabled in config.

1.8.0 BETA 6

**Comment by OmniCypher-** [comment]
@RoboMWM, Can I get this re-confirmed with ProjectKorra 1.8.0?
