### ISSUE TITLE
Attempting to repeatedly rise above max air/water/sand spout height triggers NCP survivalfly checks

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#375]
Instead of disabling and enabling fly-mode entirely when player is attempting to fly past the maximum possible height, is it possible to instead toggle the player from flying and not flying instead? This would make it compatible with anticheat plugins like NCP, which is picking up violations when the player's fly mode is disabled when they attempt to go beyond max height of the spout.

**Comment by jedk1** [comment]
The thing is, PK does use some stuff that would be picked up by nocheat etc as it would appear kinda hackish, A personal fix i find to this is to just loosen up  the nocheat config in the worlds where i have bending enabled.

**Comment by RoboMWM** [comment]
That's what I've been doing - I think I've nerfed the survivalfly check to the point where only "extreme" hacking would be detected. Either way it seems that I can no longer trigger this one after a couple of changes to NCP (or perhaps updates to NCP builds).

Either way I'm under the assumption that it's possible to just toggle whether the player is flying, not flymode entirely, as then they'd be checked by NCP's creativefly check instead of racking violations for survivalfly.

**Comment by RoboMWM** [comment]
Upon further self-thinking, I figured that NCP will probably check via the appropriate fly check even if you "allow" flying. Perhaps a temporary exemption would be better suited here (only exempt if it's possible for the spout to automatically re-activate without clicking, i.e. if not suddenly over too great of a height)
