### ISSUE TITLE
AirSpout allows for infinite flying when touched by another player's tornado

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#377]
To reproduce:
1. Start flying via airspout
2. Have another player use tornado on you.

(I'm not sure if you have to be thrown to a height where airspout doesn't work.)

You will then no longer be using airSpout, but will still be in fly mode.

1.8.0 BETA 6

**Comment by OmniCypher-** [comment]
@RoboMWM, Can I get this re-confirmed with ProjectKorra 1.8.0?

**Comment by PhanaticD** [comment]
this works with your own tornado too, we tested it on the test server with sobki

**Comment by RoboMWM** [comment]
Thanks PhanaticD, haven't had time to reconfirm these bugs so I appreciate that.

**Comment by 0ct0ber** [comment]
Has anyone confirmed that this is still a bug in 1.8.6?

**Comment by ChristopherWMM** [comment]
Yes, and it is marked as in-progress so someone is actively working on it.
