### ISSUE TITLE
Airbender sprint effects are permanent after teleport

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#378]
If an airbender is sprinting while teleported (such as entering a Multiverse-Portal), the airbender will have the speed and jump boost effects permanently until they sprint again.

**Comment by jedk1** [comment]
Can you provide any more information on this? 
Does the world they are moving to have bending disabled?
Do they move into a region where passive bending is disabled?
Any logs you can provide?

**Comment by RoboMWM** [comment]
Well the initial world has bending disabled, however it seems passive abilities are still functional in that world.

What sort of logs would you be looking for?

**Comment by StrangeOne101** [comment]
Is this still an issue?

**Comment by RoboMWM** [comment]
As far as I'm aware, passive abilities no longer function in disabled worlds, correct? If so, then I don't think this is an issue.

**Comment by RoboMWM** [comment]
Actually just happened when someone accepted my teleport request. I was in a world where bending is disabled, sprinting around, and was teleported, with infinite speed potion effect until I sprinted in the new world.

**Comment by ChristopherWMM** [comment]
I am not able to replicate this bug. Does the world you teleport to/from need to be disabled or are the passives become permanent after any sprinting teleport?

**Comment by RoboMWM** [comment]
In both cases, the world I was teleported from has bending disabled for that world. I use a different teleport system (at least for /tpa's) so chances of it happening are very nil. My guess as to what is happening though is after the teleport, PlayerToggleSprintEvent is fired after the player arrives in the world, and only once (toggling off, since they aren't moving, usually). Checking `event#isSprinting` should be sufficient if this single toggle is the case (since I suppose it might be relying solely on player#isSprinting - not sure how this info changes on a worldchange/teleport in correspondence with the event).

**Comment by RoboMWM** [comment]
Via a quick github search, it seems there's only one case where `event#isSneaking` is used. Everywhere else in PlayerToggleSneakEvent is the use of `player#isSneaking`.

**Comment by RoboMWM** [comment]
Hmm, it seems passives (at least now) operate via just checking player state every tick instead of monitoring events. Therefore it's likely that this is fixed. (Just tested quickly myself, seems to not be easily reproducible at least.)
