### ISSUE TITLE
Use of /bending remove doesn't save to database

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#380]
I've used /bending remove on myself and other players, but it seems that this is not preserved between server restarts. I do not see any log messages in console, and in-game the player does indeed lose the ability to bend the removed element (or at all) - but after a restart, the removed ability is re-instated.

Using /bending choose and /bending add seem to save properly.

1.8.0 BETA 6 (using default storage, SQLite)

**Comment by OmniCypher-** [comment]
It appears as though this is fixed, but please reopen this is you still see it happening in the latest build
