### ISSUE TITLE
Dynamic and Auto Sourcing

### ISSUE THREAD

**Issue by Chaotic-Dev** [ProjectKorra/ProjectKorra#565]
You have forgotten to add the code and config options needed to disable the dynamic and auto sourcing features.

So here's an idea for your next PR: add them back :)

**Comment by StrangeOne101** [comment]
Auto-sourcing has been long since removed anyway, so there's no issue there. Being able to disable dynamic sourcing is on the To-Do list, but right now we're focusing on bugs.
