### ISSUE TITLE
IllegalArgumentException: Cannot make player fly if getAllowFlight() is false in AirFlight.java

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#601]
http://pastebin.com/raw/Kcif5Y3Q

**Comment by Sobki** [comment]
What is it you did to trigger this? I can't see to get the error to occur when using flight, and hovering.

**Comment by PhanaticD** [comment]
I have no idea, I just see it on console, I have over 20-80 players on usually so its hard to tell who is doing what.

**Comment by OmniCypher-** [comment]
Seems like adding a `player.setAllowFlight(true);` above line 84 of `AirFlight` will do the trick, it's a little odd that directly setting a player into flight mode would get denied like that.
