### ISSUE TITLE
NPE surgewave thaw animation event

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#603]
http://pastebin.com/Shjqx1Kx

**Comment by Sobki** [comment]
Again, I can't see to trigger this when using surge wave, freezing mobs, and thawing it. What was it you did?

**Comment by PhanaticD** [comment]
I have no idea, I just see it on console, I have over 20-80 players on usually so its hard to tell who is doing what.

**Comment by PhanaticD** [comment]
another error probably related http://pastebin.com/UFncQf8U
