### ISSUE TITLE
NPE remove spouts

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#604]
http://pastebin.com/JnXMUHmy

**Comment by Sobki** [comment]
Like the previous two, I can't seem to trigger this one either. Make sure you're using the right version of the plugin with the right version of MC. I'll look at the other issues once I've heard back from you, because I can't seem to get it to happen.

**Comment by PhanaticD** [comment]
I have no idea, I just see it on console, I have over 20-80 players on usually so its hard to tell who is doing what. 

I am using the right version
