### ISSUE TITLE
llegalArgumentException on ParticleEffect.WATER_BUBBLE in Torrent.java

### ISSUE THREAD

**Issue by PhanaticD** [ProjectKorra/ProjectKorra#614]
http://pastebin.com/raw/s1q0cKRn

spammed console a bit

**Comment by Sobki** [comment]
Can't replicate this one either.

**Comment by PhanaticD** [comment]
It happens I did not pull it out of nowhere

**Comment by Sobki** [comment]
If you figure out how to replicate any of these, please let me know. I can't seem to do it using any feature of the abilities. What MC version and PK version?

**Comment by PhanaticD** [comment]
1.10.2 and 1.8

**Comment by Sobki** [comment]
Are you using the most recent version for 1.10?

**Comment by PhanaticD** [comment]
yes

**Comment by OmniCypher-** [comment]
Appears to be happening due to a faulty if check on line 225 of `Torrent`, with the current setup is is technically possible for the move to attempt to display the `WATER_BUBBLE` `ParticleEffect` outside water causing this error.
