### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by jchilleo** [ProjectKorra/ProjectKorra#659]
Hello there, I was wondering if I can compile my own jar of the Core?

I want to make some changes to the base abilities (airbubble, waterbubble, and earthtunnel) for exclusive use in my server. My changes remove the sneak requirement for both bubbles, and revert back line 114 to "this.block.breakNaturally();"

If you prefer me not to make these changes, could you just compile a version for me the changes?

Thanks, and sorry for using the issues panel like this.

**Comment by Loonyy** [comment]
Yeah you can do that - It's an open source.

You're not allowed to remove credits or the staff list, however.
