### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by ghost** [ProjectKorra/ProjectKorra#68]
Hey awesome plugin but i've got 2 worlds on my server at the moment, a normal one without bending and a free-for-all with bending, i use PermissionsEx for permission handling and i've given every rank 
- -bending.* (Even tried - -bending.water for this problem). However if there are any waterbenders who leave the bending world, even though they are unable to bend in the normal world or use commands, they are still getting the message every night "You feel the strength of the rising moon empowering your waterbending." this is also the case for firebenders during the day.
I was unable to find the editable message in the config. If this could be fixed that would be awesome :)

**Comment by OmniCypher-** [comment]
So if a read correctly, if players are in the normal world (where they can't bend) they will still receive the day and night messages?

**Comment by curz46** [comment]
@OmniCypher- old and abandoned, needs to be closed.
