### ISSUE TITLE
Cannot use Blaze ability if not opped

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#796]
Tested on a server with just https://github.com/ProjectKorra/ProjectKorra/commit/e9f4195a67644c9c25f1dfca5f4829ec7e788a84 installed, and I was unable to use the Blaze ability as a firebender. I'm able to bind it, but nothing happens when clicking or sneaking - unless if I'm opped. 

I Tried manually setting `bending.ability.blaze` via luckperms, that didn't work either. Not sure what else it could be, I went through the logic briefly a couple times albeit I'm not fully familiar with this codebase.

**Comment by Loonyy** [comment]
Can they use FireBlast?
Make sure WorldGuard is updated and that you have lighter and TNT set to allow.

**Comment by OmniCypher-** [comment]
The issue has been isolated and we are working on a solution. Thanks for the report.

**Comment by RoboMWM** [comment]
Thanks for letting me know. Regarding @Loonyy's question, this was tested on a server with no other plugins.

**Comment by OmniCypher-** [comment]
Fixed as of 1.8.5.
