### ISSUE TITLE
Temporary blocks issue (noticable with illumination)

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#838]
To reproduce:
1. Have illumination be active (dark enough)
2. Jump, break the torch beneath you and immediately place a block underneath you.
3. Observe the torch breaking as an item (the block disappears) that you can pick up.

Suggestions:
- Use `player#sendBlockChange` (or w/e it's called) for nearby players instead of placing a block into the world and having to deal with all of its effects such as block physics updates, etc. (including plugins that move blocks like autocraft).

**Comment by PhanaticD** [comment]
doesnt happen for me

**Comment by ChristopherWMM** [comment]
I cannot replicate this specific behavior while on the latest version either. However, there are quite a few of other cases what cause the torch to break and drop such as placing water on it. I don't see why we aren't using `Player::sendBlockChange`.

**Comment by RoboMWM** [comment]
Yea, can't reproduce either. I believe I was on the wip branch (if there was one) back then. But, as you also mentioned in your comment (and as I hinted to in my OP) it can be broken and picked up via flowing water.

Apparently there is also a way to simply send lighting updates to clients so you don't have to spawn a lighting source (fake or real), but will likely require reflection/NMS and I have no idea how performant it is.

**Comment by PhanaticD** [comment]
this plugin could be used maybe but I think it might be outdated, I use it for that furniture plugin https://www.spigotmc.org/resources/lightapi.4510/

**Comment by RoboMWM** [comment]
Ah yea that's the plugin (or API, rather) that I was remembering. Likely not worth the trouble though.

**Comment by ChristopherWMM** [comment]
This seems to be the real "meat and potatoes" of the logic behind the API. https://github.com/BeYkeRYkt/LightAPI/blob/3.0/src/ru/beykerykt/lightapi/server/nms/craftbukkit/CraftBukkit_v1_12_R1.java#L20-L37

**Comment by Varhagna** [comment]
Closed by #1070
