### ISSUE TITLE
AirBlast bypasses protected doors, levers and buttons

### ISSUE THREAD

**Issue by jontymorris** [ProjectKorra/ProjectKorra#856]
Players can use AirBlast on protected buttons, doors or levers.

For example, a player can come into a random faction and control the doors, levers and buttons by using AirBlast. AirBlast is bypassing the faction protection.

I think it would be a good idea if the AirBlast config had an option that disables the altering of protected buttons, doors or levers.

**Comment by StrangeOne101** [comment]
AirBlast shouldn't be usable in a faction that the player doesn't have permission to build in. Is faction protection for bending enabled?

If so, the fact that they can use it in a faction that they don't have permission for is a rather large issue.

**Comment by jontymorris** [comment]
Alright, it sounds like there isn't a problem then.
Faction protection for bending is disabled.
