### ISSUE TITLE
Task #332 generated an exception

### ISSUE THREAD

**Issue by FatherWh0** [ProjectKorra/ProjectKorra#876]
Running a compile of the wip compiled 1-4.
https://hastebin.com/menucuvuvu.vbs
Haven't determined what starts the errors but once they begin they continue endlessly until restart.

**Comment by plushmonkey** [comment]
This isn't a ProjectKorra bug. You're using a version of JedCore that isn't meant to be used with the wip branch.

**Comment by ChristopherWMM** [comment]
As stated by @plushmonkey, this is not an issue with ProjectKorra.
