### ISSUE TITLE
Fix project file

### ISSUE THREAD

**Issue by killme** [ProjectKorra/ProjectKorra#88]
![screenshot - 180115 - 00 07 13](https://cloud.githubusercontent.com/assets/1255353/5790719/2ed03384-9ea6-11e4-9f35-eafa2ae47675.png)

As you can see, the project file is currently unusable by anyone but you.
Could you please fix that?

**Comment by jacklin213** [comment]
Just remove those dependencies and import yours. Make your you do not sync your .classpath while making a pull request
