### ISSUE TITLE
AvatarState bug

### ISSUE THREAD

**Issue by Admiral-BSKL** [ProjectKorra/ProjectKorra#888]
Whenever an op uses AvatarState on my server, it can only be used 1 time. Then we have to reload/restart the server to get AvatarState working again.

**Comment by xNuminousx** [comment]
This is probably an issue with your cooldown. In my experience, lessening the cooldown fixes this.

**Comment by Admiral-BSKL** [comment]
Will check it out, thanks. Forgot to modify the cooldown for avatarstate.

**Comment by ChristopherWMM** [comment]
Marking as resolved.
