### ISSUE TITLE
Surge is able to break any block including Bedrock and Barriers

### ISSUE THREAD

**Issue by imxari** [ProjectKorra/ProjectKorra#906]
Hello,

Recently the players on our bending server have revealed to us a method of being able to break any block with Surge. The method to reproduce this is to Click Water with Surge, Shift and Spam click a block this will cause the block to break/disappear. Could this please be looked into!

Thanks
H0lysp4nk

**Comment by xNuminousx** [comment]
If the problem is spam, a temporary solution could be to put a small cooldown on the ability which prevents players from using it so rapidly. That is, if I’m understanding the issue.

**Comment by h0lysp4nk** [comment]
Ok, I shall do that now!

**Comment by ChristopherWMM** [comment]
The issue with that is it doesn't actually solve the issue, only masks the underlying problem. We don't typically accept pull requests that just patch.

**Comment by xNuminousx** [comment]
Well I said it was a temporary solution while this gets worked on and this is an issue post not a PR so idk why you say that.

**Comment by ChristopherWMM** [comment]
I am aware, I just wanted to make it clear that if either of you did submit that as a pull request it wouldn't be accepted.

**Comment by Simplicitee** [comment]
Do you have evidence of this working, I am unable to recreate it.

**Comment by h0lysp4nk** [comment]
It doesn't happen everytime but it is possible to do

**Comment by xNuminousx** [comment]
Could you say which Pk version you're using? I realize it's not stated anywhere.

**Comment by h0lysp4nk** [comment]
I'm using 1.8.6

**Comment by Varhagna** [comment]
I attempted to recreate this but was unable to do so on the latest version.
