### ISSUE TITLE
AirBlast not functioning on buttons/levers

### ISSUE THREAD

**Issue by fotoply** [ProjectKorra/ProjectKorra#92]
I was recently testing building a door which was openable only by airbendingen, when I noticed that buttons and levers are not affected by airblasts, even though the description details that they should be able to activate them.
It seems that in the code, the part for handling this has been commented out, for some reason not stated.

So either the description of the ability should be edited or the code fixed, so that these two match again.

**Comment by OmniCypher-** [comment]
Fixed as of the latest version.
