### ISSUE TITLE
Bug with water bottles

### ISSUE THREAD

**Issue by 0ct0ber** [ProjectKorra/ProjectKorra#920]
Some of you may know this bug already, but I think it's worth everyone knowing about. On the official server and some other servers, I have seen that most water moves which are supposed to have the option to have water bottles as the water source aren't working with water bottles. This limits waterbenders much more than is intentional to fighting by or in the water bodies. I've observed this on servers with the latest version of ProjectKorra as well.

This has been going on for quite a while, and as a result I'm guessing on some servers players are strategizing around it. Perhaps if people want, when this bug is fixed moves that involve the bottle option have it disableable in the config (per-move).

Edit: The moves affected by this are Surge, WaterArms and possibly Torrent.

**Comment by Varhagna** [comment]
I'm closing this issue since it has been two years and this in particular has been fixed.
