### ISSUE TITLE
ProjectKorra hogging the actionbar

### ISSUE THREAD

**Issue by RoboMWM** [ProjectKorra/ProjectKorra#936]
So it seems ProjectKorra now incessantly spams the actionbar with an empty string if it has nothing to show... which prevents any other plugin from using this :( 

Please revert the behavior where ProjectKorra would only send actionbar messages when it has something to display.

Using https://github.com/ProjectKorra/ProjectKorra/commit/41a52d03e59b92e8bfec81c41a0c2ded45992e6d with my patch to disable the update checker https://github.com/MLG-Fortress/ProjectKorra/commit/7bda2f511fa781388162f300c6e3c4e81bd852fc

**Comment by FinnBueno** [comment]
Update checker fix has already been submitted. We'll look into the actionbar! Thanks for bringing this to our attention.

**Comment by RoboMWM** [comment]
Yea, I prefer the old way that only shows when switched to, and when active/cooldown reset (though I don't mind the cooldown countdown, since the player is using the abilities they probably care/find that info relevant in the actionbar compared to other things.

**Comment by Varhagna** [comment]
I'm going to close this since it has been two years, if your issue persists in the current version please feel free to recreate your issue or pm a staff member to reopen this one :)
