### ISSUE TITLE
Entity Errors

### ISSUE THREAD

**Issue by Kirrasio** [ProjectKorra/ProjectKorra#938]
This used to be only occurring when users would use lava flow, however it is now just happening randomly. The first is my newest error log.

https://pastebin.com/DaThZ0M8

Older:
https://pastebin.com/TSarWGkm

https://pastebin.com/bvs2KKBy

Spigot 1.12.2 

PK : ProjectKorra-1.8.6

**Comment by ArchBear-Vega** [comment]
If you could give a detailed description of what you are doing when this error happens that would be super great, as well as your PK Debug. I have a feeling I think I know whats going on but I would need the debug to confirm it.

Thanks

**Comment by Varhagna** [comment]
I'm closing this since it is outdated. If this issue still persists in the latest version please feel free to recreate your issue with updated error logs and a PK Debug.
