### ISSUE TITLE
Fire tick damage knocking back entities

### ISSUE THREAD

**Issue by 0ct0ber** [ProjectKorra/ProjectKorra#975]
Creatures and players seem to be knocked back and upwards by fire from abilities when lit by it... this was a bug in earlier versions of minecraft, but seems to be re-created in 1.12.2, PK 1.8.7.

![knockback creeper](https://user-images.githubusercontent.com/10884689/44043354-85e43780-9ed7-11e8-9f76-fead24711dac.gif)

**Comment by Simplicitee** [comment]
Burn damage or straight damage from firebending?

**Comment by 0ct0ber** [comment]
@Simplicitee Yes, damage due to fire ticks. Thanks for pointing that out.

**Comment by Simplicitee** [comment]
If it's fire tick, isn't that normal? If it's fire tick, then there's nothing we can do about it, that's a mc problem, if it's even a problem. That is something that I've always seen in mc.

**Comment by xNuminousx** [comment]
Applied damage (fire, potion, arrow) has always done knockback to it's targets.

**Comment by 0ct0ber** [comment]
@xNuminousx @Simplicitee It was fixed in a not recent version; I've tested it on singleplayer and the same server I tested PK on, and if I use a regular fire aspect sword or flint and steel, the mobs won't take knockback from the fire ticks. But as soon as I use FireBlast on them, they're knocked back multiple times by the burn damage.

I've added a gif to show this.

![knockback creeper](https://user-images.githubusercontent.com/10884689/44043354-85e43780-9ed7-11e8-9f76-fead24711dac.gif)

**Comment by Simplicitee** [comment]
I see. Looking at the code, this is intentional.

For firebending and the burn it applies, it actually cancels the damage event and then damages the entity as normal damage. It's replicating the damage of burn so that it can be tracked that it was indeed firebending burn that damaged the entity. This is used in various places such as death messages and damage tracking itself. Normal damage applies the knockback, and as such it will here too.

**Comment by Varhagna** [comment]
This will most likely not be fixed then? Its a good note to address for the overhaul but since this most likely won't be fixed for 1.9.0 and since this issue has been around for a while I'm closing it.
