### ISSUE TITLE
JetBlast and JetBlaze use FireJet's cooldown

### ISSUE THREAD

**Issue by 0ct0ber** [ProjectKorra/ProjectKorra#976]
JetBlast and JetBlaze aren't using independent cooldowns; they stay the same as FireJet's, and are only changed when the cooldown for FireJet is changed.

**Comment by Simplicitee** [comment]
Both JetBlast and JetBlaze use FireJet as a base, modifying it's parameters to fit the combos' needs. This is not an issue, simply how they work which is intentional.

**Comment by 0ct0ber** [comment]
@Simplicitee I believe it is intentional for their cooldowns in the configuration file to actually work... if I set JetBlaze's cooldown to 10 seconds, and FireJet's to 2, JetBlaze takes two seconds before it's usable again.

**Comment by Simplicitee** [comment]
Ah I see what you mean. Thank you for reporting this.

**Comment by Varhagna** [comment]
I'm closing this issue since it has been over two years. If this issue persists please feel free to recreate it or message me and I will reopen it.
